/*konta*/
INSERT INTO KONTO VALUES (null,'janusz','tracz',1,89.8,167,1);
INSERT INTO KONTO VALUES (null,'miachu','tracz',1,88,177,1);
INSERT INTO KONTO VALUES (null,'paweu','tracz',1,89.8,166,1);
INSERT INTO KONTO VALUES (null,'kamien','tracz',1,89.8,187,1);
INSERT INTO KONTO VALUES (null,'kremówka','tracz',0,89.8,167,0);
INSERT INTO KONTO VALUES (null,'cebula','tracz',0,69.8,165,0);
INSERT INTO KONTO VALUES (null,'julka','tracz',0,70.8,175,1);
INSERT INTO KONTO VALUES (null,'Aśka','tracz',0,65.5,16,1);
commit;

/*znajomi*/
INSERT INTO ZNAJOMI VALUES (2,1);
INSERT INTO ZNAJOMI VALUES (3,1);
INSERT INTO ZNAJOMI VALUES (4,1);
INSERT INTO ZNAJOMI VALUES (7,2);
commit;


INSERT INTO TYP_AKTYWNOSCI VALUES (1,'plywanie');
INSERT INTO TYP_AKTYWNOSCI VALUES (2,'bieg');
INSERT INTO TYP_AKTYWNOSCI VALUES (3,'rower');


INSERT INTO WYZWANIE VALUES (null,'XD',1,CURRENT_DATE,CURRENT_DATE+7,
                             0,1000,'km',1,1);
INSERT INTO WYZWANIE VALUES (null,'wyzwanie2',1,CURRENT_DATE,CURRENT_DATE+1,
                             0,100,'km',1,2);
INSERT INTO WYZWANIE VALUES (null,'rower',1,CURRENT_DATE,CURRENT_DATE+30,
                             0,1337,'km',1,3);


INSERT INTO UCZESTNICY_WYZWANIA VALUES (1,1);
INSERT INTO UCZESTNICY_WYZWANIA VALUES (2,1);
INSERT INTO UCZESTNICY_WYZWANIA VALUES (3,1);

INSERT INTO UCZESTNICY_WYZWANIA VALUES (1,2);
INSERT INTO UCZESTNICY_WYZWANIA VALUES (1,2);

INSERT INTO AKTYWNOSC VALUES (1,1,2,CURRENT_DATE,120);
INSERT INTO AKTYWNOSC VALUES (1,1,0.3,CURRENT_DATE, 24);
INSERT INTO AKTYWNOSC VALUES (2,1,3,CURRENT_DATE,12);

INSERT INTO AKTYWNOSC VALUES (1,2,0.3,CURRENT_DATE, 24);
INSERT INTO AKTYWNOSC VALUES (2,2,3,CURRENT_DATE,12);

INSERT INTO AKTYWNOSC VALUES (1,3,30,CURRENT_DATE,60);
commit;